### ISSUE TITLE
RuntimeError: no running event loop sys:1

### ISSUE THREAD

**Issue by alfirin** [freqtrade/ftui#12] opened 2024-12-03 19:33 UTC
Hello I believe it can be the same error as another opened issue, but in doubt as there is no message in the other, I created a new one.

The bug: in latest version, it's working with the All view, but when I click on the bot View here is the error:

![Image](https://github.com/user-attachments/assets/5db61080-67f7-4bab-8abb-31ef4345b478)

Full stack:

```
/home/ubuntuy/github/ftui/.venv/lib/python3.12/site-packages/textual/widget.py:889 in _watch_loading                                                                                       │
│                                                                                                                                                                                          │
│    886 │                                                                                        ╭─────────────── locals ────────────────╮                                                │
│    887 │   def _watch_loading(self, loading: bool) -> None:                                     │ loading = True                        │                                                │
│    888 │   │   """Called when the 'loading' reactive is changed."""                             │    self = PlotextPlot(id='bot-chart') │                                                │
│ ❱  889 │   │   self.set_loading(loading)                                                        ╰───────────────────────────────────────╯                                                │
│    890 │                                                                                                                                                                                 │
│    891 │   ExpectType = TypeVar("ExpectType", bound="Widget")                                                                                                                            │
│    892                                                                                                                                                                                   │
│                                                                                                                                                                                          │
│ /home/ubuntuy/github/ftui/.venv/lib/python3.12/site-packages/textual/widget.py:883 in set_loading                                                                                          │
│                                                                                                                                                                                          │
│    880 │   │   if loading:                                                                      ╭──────────────────────── locals ────────────────────────╮                               │
│    881 │   │   │   loading_indicator = self.get_loading_widget()                                │                 loading = True                         │                               │
│    882 │   │   │   loading_indicator.add_class(LOADING_INDICATOR_CLASS)                         │       loading_indicator = LoadingIndicator()           │                               │
│ ❱  883 │   │   │   self._cover(loading_indicator)                                               │ LOADING_INDICATOR_CLASS = '-textual-loading-indicator' │                               │
│    884 │   │   else:                                                                            │                    self = PlotextPlot(id='bot-chart')  │                               │
│    885 │   │   │   self._uncover()                                                              ╰────────────────────────────────────────────────────────╯                               │
│    886                                                                                                                                                                                   │
│                                                                                                                                                                                          │
│ /home/ubuntuy/github/ftui/.venv/lib/python3.12/site-packages/textual/widget.py:632 in _cover                                                                                               │
│                                                                                                                                                                                          │
│    629 │   │   self._uncover()                                                                  ╭─────────────── locals ───────────────╮                                                 │
│    630 │   │   self._cover_widget = widget                                                      │   self = PlotextPlot(id='bot-chart') │                                                 │
│    631 │   │   widget._parent = self                                                            │ widget = LoadingIndicator()          │                                                 │
│ ❱  632 │   │   widget._start_messages()                                                         ╰──────────────────────────────────────╯                                                 │
│    633 │   │   widget._post_register(self.app)                                                                                                                                           │
│    634 │   │   self.app.stylesheet.apply(widget)                                                                                                                                         │
│    635 │   │   self.refresh(layout=True)                                                                                                                                                 │
│                                                                                                                                                                                          │
│ /home/ubuntuy/github/ftui/.venv/lib/python3.12/site-packages/textual/message_pump.py:497 in _start_messages                                                                                │
│                                                                                                                                                                                          │
│   494 │   def _start_messages(self) -> None:                                                   ╭───────── locals ──────────╮                                                             │
│   495 │   │   """Start messages task."""                                                       │ self = LoadingIndicator() │                                                             │
│   496 │   │   if self.app._running:                                                            ╰───────────────────────────╯                                                             │
│ ❱ 497 │   │   │   self._task = create_task(                                                                                                                                              │
│   498 │   │   │   │   self._process_messages(), name=f"message pump {self}"                                                                                                              │
│   499 │   │   │   )                                                                                                                                                                      │
│   500 │   │   else:                                                                                                                                                                      │
│                                                                                                                                                                                          │
│ /usr/lib/python3.12/asyncio/tasks.py:417 in create_task                                                                                                                                  │
│                                                                                                                                                                                          │
│    414 │                                                                                        ╭─────────────────────────────────── locals ───────────────────────────────────╮         │
│    415 │   Return a Task object.                                                                │ context = None                                                               │         │
│    416 │   """                                                                                  │    coro = <coroutine object MessagePump._process_messages at 0x7ffb3447f2e0> │         │
│ ❱  417 │   loop = events.get_running_loop()                                                     │    name = 'message pump LoadingIndicator()'                                  │         │
│    418 │   if context is None:                                                                  ╰──────────────────────────────────────────────────────────────────────────────╯         │
│    419 │   │   # Use legacy API if context is not needed                                                                                                                                 │
│    420 │   │   task = loop.create_task(coro)                                                                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'MessagePump._process_messages' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by froggleston** [comment] 2024-12-05 14:47
Caused by https://github.com/Textualize/textual/issues/5262 - will push a fix soon. Duplicate of #10 .

**Comment by froggleston** [comment] 2024-12-05 16:06
Fixed in https://github.com/freqtrade/ftui/commit/6ad4cf52ef7245a9f97cf4d3be00ef5110175a06

**Closed by froggleston** 2024-12-05 16:06 UTC
